/** Durable task event types (spec §106). Timeline is reconstructed by ordering on (timestamp, sequence). */
export const TASK_EVENT_TYPES = [
  'TaskCreated',
  'TaskQueued',
  'TaskOffered',
  'TaskClaimed',
  'TaskStarted',
  'TaskStatusChanged',
  'TaskProgress',
  'TaskPaused',
  'TaskResumed',
  'TaskCancelled',
  'TaskRetried',
  'TaskRequeued',
  'LeaseExpired',
  'WorkerLost',
  'CapabilityPlanCreated',
  'PluginHookCompleted',
  'PluginHookFailed',
  'ApprovalRequested',
  'ApprovalGranted',
  'ApprovalDenied',
  'AgentStarted',
  'AgentOutput',
  'AgentStateChanged',
  'AgentInputRequested',
  'AgentInputProvided',
  'AgentExited',
  'AgentCrashed',
  'AgentHangSuspected',
  'CommandExecuted',
  'FileChanged',
  'ProviderLimitDetected',
  'ContextExhausted',
  'CheckpointCreated',
  'FallbackStarted',
  'SessionResumed',
  'VerificationStarted',
  'VerificationStepCompleted',
  'VerificationPassed',
  'VerificationFailed',
  'RemediationStarted',
  'GitCommitCreated',
  'GitPushed',
  'GitOperationBlocked',
  'TaskCompleted',
  'TaskFailed',
  'RecoveryRequired',
] as const;
export type TaskEventType = (typeof TASK_EVENT_TYPES)[number];

/** Event types delivered live but not required for audit-grade timeline (can be sampled/retained shorter). */
export const EPHEMERAL_EVENT_TYPES: readonly TaskEventType[] = ['AgentOutput', 'TaskProgress'];
